// Golden-vector tests for the Midea protocol layers.
//
// Every expected value was generated by msmart itself (GetStateCommand,
// SetStateCommand, ToggleDisplayCommand, StateResponse, _Packet,
// _LanProtocolV3) rather than by this port — see tools/gen_vectors.py. A
// mistake in the port therefore fails a test instead of being baked into the
// fixture.

#include <string.h>
#include <unity.h>

#include "proto/midea_command.h"
#include "proto/midea_frame.h"
#include "proto/midea_packet.h"

using namespace acbridge::proto;

namespace {

size_t unhexM(const char* hex, uint8_t* out, size_t cap) {
  const size_t n = strlen(hex) / 2;
  if (n > cap) return 0;
  for (size_t i = 0; i < n; i++) {
    auto nib = [](char c) -> uint8_t {
      if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
      if (c >= 'a' && c <= 'f') return static_cast<uint8_t>(c - 'a' + 10);
      return static_cast<uint8_t>(c - 'A' + 10);
    };
    out[i] = static_cast<uint8_t>((nib(hex[i * 2]) << 4) | nib(hex[i * 2 + 1]));
  }
  return n;
}

void assertHex(const char* expected_hex, const uint8_t* actual, size_t actual_len) {
  uint8_t expected[128];
  const size_t expected_len = unhexM(expected_hex, expected, sizeof(expected));
  TEST_ASSERT_NOT_EQUAL(0, expected_len);
  TEST_ASSERT_EQUAL_size_t(expected_len, actual_len);
  TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, actual, expected_len);
}

}  // namespace

// -- Frame -------------------------------------------------------------------

void test_frame_checksum(void) {
  // (~sum + 1) & 0xFF
  const uint8_t data[] = {0x01, 0x02, 0x03};
  TEST_ASSERT_EQUAL_UINT8(0xFA, frameChecksum(data, sizeof(data)));
  TEST_ASSERT_EQUAL_UINT8(0x00, frameChecksum(nullptr, 0));
}

void test_frame_roundtrip_validates(void) {
  const uint8_t data[] = {0xC0, 0x01, 0x02};
  uint8_t frame[32];
  const size_t len = buildFrame(frame, sizeof(frame), kFrameQuery, data, sizeof(data));
  TEST_ASSERT_EQUAL_size_t(kFrameHeaderLen + sizeof(data) + 1, len);
  TEST_ASSERT_TRUE(validateFrame(frame, len));

  TEST_ASSERT_EQUAL_UINT8(0xAA, frame[0]);
  TEST_ASSERT_EQUAL_UINT8(kFrameHeaderLen + sizeof(data), frame[1]);
  TEST_ASSERT_EQUAL_UINT8(kDeviceTypeAc, frame[2]);
  TEST_ASSERT_EQUAL_UINT8(kFrameQuery, frame[9]);
}

void test_frame_rejects_corruption(void) {
  const uint8_t data[] = {0xC0, 0x01, 0x02};
  uint8_t frame[32];
  const size_t len = buildFrame(frame, sizeof(frame), kFrameQuery, data, sizeof(data));

  uint8_t bad[32];
  memcpy(bad, frame, len);
  bad[12] ^= 0xFF;
  TEST_ASSERT_FALSE(validateFrame(bad, len));

  memcpy(bad, frame, len);
  bad[2] = 0xCC;  // wrong device type
  TEST_ASSERT_FALSE(validateFrame(bad, len));
}

// -- Commands ----------------------------------------------------------------

void test_get_state_frame(void) {
  uint8_t frame[64];
  const size_t len = buildGetStateFrame(frame, sizeof(frame), 0x01);
  assertHex("aa21ac00000000000003418100ff03ff0002000000000000000000000000030169fe", frame, len);
}

void test_toggle_display_frame(void) {
  uint8_t frame[64];
  const size_t len = buildToggleDisplayFrame(frame, sizeof(frame), 0x01, /*beep=*/true);
  assertHex("aa21ac00000000000003414200ff020002000000000000000000000000000001e6c3", frame, len);
}

void test_set_state_cool_22(void) {
  SetState s;
  s.beep = true;
  s.power = true;
  s.target_temp = 22.0f;
  s.mode = kModeCool;
  s.fan_speed = kFanAuto;
  s.swing_mode = kSwingVertical;
  s.target_humidity = 40;

  uint8_t frame[64];
  const size_t len = buildSetStateFrame(frame, sizeof(frame), s, 0x01);
  assertHex("aa24ac00000000000002404346667f7f003c00000000000000000000002800000000015646", frame,
            len);
}

// Half degrees, every flag on, and both turbo bits.
void test_set_state_heat_25_5_all_flags(void) {
  SetState s;
  s.beep = false;
  s.power = false;
  s.target_temp = 25.5f;
  s.mode = kModeHeat;
  s.fan_speed = kFanMedium;
  s.swing_mode = kSwingBoth;
  s.eco = true;
  s.turbo = true;
  s.sleep = true;
  s.fahrenheit = false;
  s.freeze_protection = true;
  s.follow_me = true;
  s.purifier = true;
  s.target_humidity = 55;

  uint8_t frame[64];
  const size_t len = buildSetStateFrame(frame, sizeof(frame), s, 0x42);
  assertHex("aa24ac000000000000024002993c7f7f003fa0a0030000000000000000370080000042e1bd", frame,
            len);
}

// 16 degrees falls outside the primary 17-30 range and moves to the alternate
// temperature byte at [18].
void test_set_state_uses_alternate_temperature(void) {
  SetState s;
  s.beep = true;
  s.power = true;
  s.target_temp = 16.0f;
  s.mode = kModeCool;
  s.fan_speed = kFanLow;
  s.swing_mode = kSwingOff;
  s.target_humidity = 40;

  uint8_t frame[64];
  const size_t len = buildSetStateFrame(frame, sizeof(frame), s, 0x01);
  assertHex("aa24ac00000000000002404340287f7f003000000000000000000000042800000000017c6c", frame,
            len);
  TEST_ASSERT_EQUAL_UINT8(0x04, frame[kFrameHeaderLen + 18]);
  TEST_ASSERT_EQUAL_UINT8(0x40, frame[kFrameHeaderLen + 2]);  // mode only, no degrees
}

void test_command_frame_rejects_small_buffer(void) {
  uint8_t frame[8];
  TEST_ASSERT_EQUAL_size_t(0, buildGetStateFrame(frame, sizeof(frame), 1));
}

// -- State response ----------------------------------------------------------

void test_parse_state_frame(void) {
  uint8_t frame[64];
  const size_t len =
      unhexM("aa21ac00000000000004c00146660000000c000000636e00000000000028000007b6", frame,
             sizeof(frame));

  MideaState st;
  TEST_ASSERT_TRUE(parseStateFrame(frame, len, &st));

  TEST_ASSERT_TRUE(st.power);
  TEST_ASSERT_EQUAL_FLOAT(22.0f, st.target_temp);
  TEST_ASSERT_EQUAL_UINT8(kModeCool, st.mode);
  TEST_ASSERT_EQUAL_UINT8(kFanAuto, st.fan_speed);
  TEST_ASSERT_EQUAL_UINT8(kSwingVertical, st.swing_mode);

  TEST_ASSERT_TRUE(st.has_indoor);
  TEST_ASSERT_EQUAL_FLOAT(24.5f, st.indoor);
  TEST_ASSERT_TRUE(st.has_outdoor);
  TEST_ASSERT_EQUAL_FLOAT(30.0f, st.outdoor);

  TEST_ASSERT_FALSE(st.turbo);
  TEST_ASSERT_FALSE(st.eco);
  TEST_ASSERT_FALSE(st.sleep);
  TEST_ASSERT_FALSE(st.fahrenheit);
  TEST_ASSERT_TRUE(st.display_on);
  TEST_ASSERT_TRUE(st.has_humidity);
  TEST_ASSERT_EQUAL_UINT8(40, st.target_humidity);
  TEST_ASSERT_FALSE(st.freeze_protection);
  TEST_ASSERT_EQUAL_UINT8(0, st.error_code);
}

void test_parse_state_rejects_bad_payload_crc(void) {
  uint8_t frame[64];
  const size_t len =
      unhexM("aa21ac00000000000004c00146660000000c000000636e00000000000028000007b6", frame,
             sizeof(frame));
  // Flip a payload byte and repair only the outer frame checksum, so the
  // payload CRC is the thing that must catch it.
  frame[kFrameHeaderLen + 3] ^= 0xFF;
  frame[len - 1] = frameChecksum(frame + 1, len - 2);

  MideaState st;
  TEST_ASSERT_FALSE(parseStateFrame(frame, len, &st));
}

void test_parse_state_rejects_wrong_response_id(void) {
  uint8_t frame[64];
  const size_t len =
      unhexM("aa21ac00000000000004c00146660000000c000000636e00000000000028000007b6", frame,
             sizeof(frame));
  frame[kFrameHeaderLen] = 0xB5;  // CAPABILITIES, not STATE
  frame[len - 1] = frameChecksum(frame + 1, len - 2);

  MideaState st;
  TEST_ASSERT_FALSE(parseStateFrame(frame, len, &st));
}

void test_parse_state_rejects_truncated(void) {
  uint8_t frame[8] = {0xAA, 0x08, 0xAC, 0, 0, 0, 0, 0};
  MideaState st;
  TEST_ASSERT_FALSE(parseStateFrame(frame, sizeof(frame), &st));
}

// -- V2 packet ---------------------------------------------------------------

void test_v2_header(void) {
  const uint8_t ts[8] = {0x00, 0x1e, 0x0a, 0x0c, 0x0f, 0x03, 0x19, 0x14};
  uint8_t header[kV2HeaderLen];
  buildV2Header(header, 0x0123456789ULL, 48, ts);
  assertHex(
      "5a5a01116800200000000000001e0a0c0f0319148967452301000000000000000000000000000000",
      header, kV2HeaderLen);
}

void test_v2_parse(void) {
  const uint8_t ts[8] = {0};
  uint8_t packet[128];
  memset(packet, 0, sizeof(packet));
  buildV2Header(packet, 0x42, 48, ts);

  V2Layout layout;
  TEST_ASSERT_TRUE(parseV2(packet, 104, &layout));
  TEST_ASSERT_EQUAL_size_t(104, layout.total_len);
  TEST_ASSERT_EQUAL_size_t(40, layout.cipher_off);
  TEST_ASSERT_EQUAL_size_t(48, layout.cipher_len);
  TEST_ASSERT_EQUAL_size_t(88, layout.signed_len);
  TEST_ASSERT_EQUAL_size_t(88, layout.sign_off);
}

void test_v2_parse_rejects_truncated_and_bad_start(void) {
  uint8_t packet[128];
  memset(packet, 0, sizeof(packet));
  buildV2Header(packet, 0x42, 48, nullptr);

  V2Layout layout;
  // Declared 104 bytes but only 80 present.
  TEST_ASSERT_FALSE(parseV2(packet, 80, &layout));

  packet[0] = 0x00;
  TEST_ASSERT_FALSE(parseV2(packet, 104, &layout));
}

// -- V3 packet ---------------------------------------------------------------

void test_v3_pad_for(void) {
  // The 2-byte packet id counts toward alignment.
  TEST_ASSERT_EQUAL_size_t(14, v3PadFor(0));
  TEST_ASSERT_EQUAL_size_t(0, v3PadFor(14));
  TEST_ASSERT_EQUAL_size_t(15, v3PadFor(15));
  TEST_ASSERT_EQUAL_size_t(14, v3PadFor(16));
  TEST_ASSERT_EQUAL_size_t(12, v3PadFor(34));
  TEST_ASSERT_EQUAL_size_t(9, v3PadFor(37));
}

void test_v3_encrypted_request_header(void) {
  // A 34-byte frame: pad 12, size field 34 + 12 + 32 = 78.
  const size_t data_len = 34;
  const size_t pad = v3PadFor(data_len);
  uint8_t header[kV3HeaderLen];
  buildV3Header(header, static_cast<uint16_t>(data_len + pad + kV3SignLen),
                static_cast<uint8_t>(pad), kV3EncryptedRequest);
  assertHex("8370004e20c6", header, kV3HeaderLen);
}

void test_v3_handshake_request_header(void) {
  uint8_t header[kV3HeaderLen];
  buildV3Header(header, 64, 0, kV3HandshakeRequest);
  assertHex("837000402000", header, kV3HeaderLen);
}

void test_v3_header_is_big_endian(void) {
  // The V3 size field is big endian, unlike the V2 header's little endian.
  uint8_t header[kV3HeaderLen];
  buildV3Header(header, 0x1234, 0, kV3EncryptedRequest);
  TEST_ASSERT_EQUAL_UINT8(0x12, header[2]);
  TEST_ASSERT_EQUAL_UINT8(0x34, header[3]);
}

void test_v3_parse_header(void) {
  uint8_t packet[16];
  unhexM("8370004e20c6", packet, sizeof(packet));

  V3Header h;
  TEST_ASSERT_TRUE(parseV3Header(packet, kV3HeaderLen, &h));
  TEST_ASSERT_EQUAL_UINT16(78, h.size_field);
  TEST_ASSERT_EQUAL_size_t(86, h.total_len);  // size + 8
  TEST_ASSERT_EQUAL_UINT8(12, h.pad);
  TEST_ASSERT_EQUAL_UINT8(kV3EncryptedRequest, h.type);
}

void test_v3_parse_header_rejects_bad_magic(void) {
  uint8_t packet[kV3HeaderLen];
  unhexM("8370004e20c6", packet, sizeof(packet));

  V3Header h;
  packet[4] = 0x21;  // magic byte must be 0x20
  TEST_ASSERT_FALSE(parseV3Header(packet, kV3HeaderLen, &h));

  unhexM("8370004e20c6", packet, sizeof(packet));
  packet[0] = 0x00;
  TEST_ASSERT_FALSE(parseV3Header(packet, kV3HeaderLen, &h));
}
