// Midea AC over the Midea LAN protocol (TCP/6444).
//
// Ported from msmart-ng, which mpsac drives. Layering, outermost first:
//
//   V3 packet  (token/key devices only) — 0x8370, AES-CBC + SHA256
//     V2 packet                         — 0x5A5A, AES-ECB + MD5
//       appliance frame                 — 0xAA, two's-complement checksum
//         command payload               — body + message id + CRC8
//
// The framing for all of that lives in proto/ and is covered by golden vectors
// generated from msmart. This file adds the socket, the crypto and the session.

#pragma once

#include <WiFiClient.h>
#include <stdint.h>

#include "../ac_driver.h"
#include "../config_store.h"
#include "../proto/midea_command.h"
#include "../proto/midea_packet.h"

namespace acbridge {

class MideaDriver : public AcDriver {
 public:
  static constexpr size_t kBuf = 640;
  static constexpr uint32_t kConnectTimeoutMs = 5000;
  static constexpr uint32_t kReadTimeoutMs = 4000;
  // msmart expires authentication after 12 hours; renew early so a command
  // never lands on a key the device has just retired.
  static constexpr uint32_t kReauthIntervalMs = 11UL * 60UL * 60UL * 1000UL;

  explicit MideaDriver(const MideaConfig& cfg);

  const char* id() const override { return "midea"; }
  const char* name() const override { return name_; }
  Vendor vendor() const override { return Vendor::Midea; }

  bool supportsFeature(Feature f) const override;
  bool supportsAction(Action a) const override;
  bool supportsSwing(Swing) const override { return true; }

  bool poll(AcState& state) override;
  bool apply(const AcCommand& cmd, AcState& state) override;
  void reset() override;

  // Derives the V3 session key from a 64-byte handshake reply: decrypt the
  // first 32 bytes with the cloud key, check them against the trailing SHA256,
  // then XOR. Exposed so the boot self-test can exercise it without a socket.
  static bool deriveLocalKey(const uint8_t* response, size_t response_len, const uint8_t* cloud_key,
                             size_t cloud_key_len, uint8_t* out, size_t* out_len);

  // Checks the encode path against vectors generated by msmart. Returns false
  // and fills `err` on mismatch. See selftest.cpp.
  static bool selfTest(char* err, size_t err_len);

 private:
  bool ensureSession(AcState& state);
  bool connectSocket(AcState& state);
  bool handshake(AcState& state);

  // Sends an appliance frame and returns the response frame.
  bool transact(const uint8_t* frame, size_t frame_len, uint8_t* out, size_t cap, size_t* out_len,
                AcState& state);

  bool writeAll(const uint8_t* data, size_t len);
  bool readExact(uint8_t* buf, size_t n);

  bool sendV3(const uint8_t* data, size_t len, uint8_t type);
  bool recvV3(uint8_t* out, size_t cap, size_t* out_len, uint8_t* type);
  bool recvV2Raw(uint8_t* out, size_t cap, size_t* out_len);

  bool encodeV2(const uint8_t* frame, size_t len, uint8_t* out, size_t cap, size_t* out_len);
  bool decodeV2(const uint8_t* packet, size_t len, uint8_t* out, size_t cap, size_t* out_len);

  void publish(const proto::MideaState& st, AcState& out) const;

  char name_[33];
  char ip_[16];
  uint16_t port_;
  uint64_t device_id_;
  uint32_t caps_;
  float min_target_;
  float max_target_;

  uint8_t token_[80];
  size_t token_len_ = 0;
  uint8_t cloud_key_[48];
  size_t cloud_key_len_ = 0;
  uint8_t local_key_[48];
  size_t local_key_len_ = 0;

  uint8_t enc_key_[16];  // MD5 of the fixed sign key, for the V2 AES-ECB layer

  WiFiClient sock_;
  bool authenticated_ = false;
  uint32_t auth_deadline_ = 0;
  uint16_t packet_id_ = 0;
  uint8_t message_id_ = 0;

  // The set command carries whole state, so a partial PATCH has to be merged
  // onto what the unit last reported rather than sent on its own.
  proto::MideaState cached_;
  bool has_cached_ = false;
  bool beep_ = true;

  uint8_t tx_[kBuf];
  uint8_t rx_[kBuf];
  uint8_t scratch_[kBuf];
};

}  // namespace acbridge
